location = "test-client"
server_id = 3 # Adjust based on the test setup
server_address = "127.0.0.1:8003" # Adjust if necessary
summary_filepath = "./logs/client-test.json"
output_filepath = "./logs/client-test.csv"

# Define test client request patterns
[[requests]]
duration_sec = 5
requests_per_sec = 5
read_ratio = 0.5

[[requests]]
duration_sec = 10
requests_per_sec = 2
read_ratio = 0.75
